#!/usr/bin/env bash
set -e

echo "======================================================="
echo "  TinyTouch GitHub Actions TestFlight Setup Assistant  "
echo "======================================================="
echo ""
echo "To enable fully automated TestFlight releases on every push to 'main',"
echo "you need to add 5 secrets to your GitHub repository:"
echo "👉 https://github.com/tianhaoz95/TinyTouch/settings/secrets/actions"
echo ""
echo "-------------------------------------------------------"
echo "Step 1: App Store Connect API Key (Takes 1 minute)"
echo "-------------------------------------------------------"
echo "1. Go to: https://appstoreconnect.apple.com/access/integrations/api"
echo "2. Under 'Keys', click (+) to generate a new API Key."
echo "   - Name: GitHub Actions CI"
echo "   - Access: App Manager (or Admin)"
echo "3. Copy the 'Issuer ID' (UUID) and 'Key ID' (10 chars)."
echo "4. Download the AuthKey_<KeyID>.p8 file (Note: Apple only lets you download it once!)."
echo ""
echo "Secrets to add in GitHub:"
echo "  - APP_STORE_CONNECT_KEY_ID: <Key ID, e.g. 2X9R4272GC>"
echo "  - APP_STORE_CONNECT_ISSUER_ID: <Issuer ID UUID>"
echo "  - APP_STORE_CONNECT_KEY_P8: <Open the .p8 file in TextEdit, copy all text starting with -----BEGIN PRIVATE KEY----->"
echo ""
echo "-------------------------------------------------------"
echo "Step 2: Apple Distribution Certificate (.p12)"
echo "-------------------------------------------------------"
echo "1. Open Xcode -> Settings -> Accounts -> select your Apple ID."
echo "2. Click 'Manage Certificates...' in the bottom right."
echo "3. If 'Apple Distribution' is not listed, click (+) -> Apple Distribution."
echo "4. Open Keychain Access on your Mac:"
echo "   - Find 'Apple Distribution: <Your Name> (6522A974B3)'"
echo "   - Expand the arrow to see the private key under it."
echo "   - Select BOTH the certificate and the private key, right-click -> Export 2 items..."
echo "   - Save as 'dist_cert.p12' and enter an export password."
echo ""
echo "5. Once saved, encode it to base64 by running:"
echo "   base64 -i /path/to/dist_cert.p12 | pbcopy"
echo "   (This copies the entire base64 string straight to your Mac clipboard!)"
echo ""
echo "Secrets to add in GitHub:"
echo "  - BUILD_CERTIFICATE_BASE64: <Paste the base64 string from clipboard>"
echo "  - P12_PASSWORD: <The password you chose when exporting the .p12>"
echo ""
echo "-------------------------------------------------------"
echo "Once these 5 secrets are in GitHub, every push to 'main'"
echo "will automatically build, test, and release directly to"
echo "TestFlight on Apple's servers!"
echo "======================================================="
